global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'producto-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.253:8093']
  - job_name: 'orden-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.253:8094']

